// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Caribbean_Water = "Caribbean Water",
  Caribbean_Water_2 = "Caribbean Water_2",
  Classic_Bench = "Classic Bench",
  Classic_Bench_10 = "Classic Bench_10",
  Classic_Bench_11 = "Classic Bench_11",
  Classic_Bench_12 = "Classic Bench_12",
  Classic_Bench_2 = "Classic Bench_2",
  Classic_Bench_3 = "Classic Bench_3",
  Classic_Bench_5 = "Classic Bench_5",
  Classic_Bench_8 = "Classic Bench_8",
  Classic_Bench_9 = "Classic Bench_9",
  Lilypad = "Lilypad",
  Lilypad_10 = "Lilypad_10",
  Lilypad_11 = "Lilypad_11",
  Lilypad_12 = "Lilypad_12",
  Lilypad_13 = "Lilypad_13",
  Lilypad_14 = "Lilypad_14",
  Lilypad_15 = "Lilypad_15",
  Lilypad_16 = "Lilypad_16",
  Lilypad_2 = "Lilypad_2",
  Lilypad_3 = "Lilypad_3",
  Lilypad_4 = "Lilypad_4",
  Lilypad_5 = "Lilypad_5",
  Lilypad_6 = "Lilypad_6",
  Lilypad_7 = "Lilypad_7",
  Lilypad_8 = "Lilypad_8",
  Lilypad_9 = "Lilypad_9",
  Sit_Spot_1 = "Sit Spot 1",
  Sit_Spot_1_10 = "Sit Spot 1_10",
  Sit_Spot_1_11 = "Sit Spot 1_11",
  Sit_Spot_1_12 = "Sit Spot 1_12",
  Sit_Spot_1_2 = "Sit Spot 1_2",
  Sit_Spot_1_3 = "Sit Spot 1_3",
  Sit_Spot_1_5 = "Sit Spot 1_5",
  Sit_Spot_1_8 = "Sit Spot 1_8",
  Sit_Spot_1_9 = "Sit Spot 1_9",
  Sit_Spot_2 = "Sit Spot 2",
  Sit_Spot_2_10 = "Sit Spot 2_10",
  Sit_Spot_2_11 = "Sit Spot 2_11",
  Sit_Spot_2_12 = "Sit Spot 2_12",
  Sit_Spot_2_2 = "Sit Spot 2_2",
  Sit_Spot_2_3 = "Sit Spot 2_3",
  Sit_Spot_2_5 = "Sit Spot 2_5",
  Sit_Spot_2_8 = "Sit Spot 2_8",
  Sit_Spot_2_9 = "Sit Spot 2_9",
  birds_glb = "birds.glb",
  castle_glb = "castle.glb",
  lights_glb = "lights.glb",
  plants_glb = "plants.glb",
  props_glb = "props.glb",
} 
